//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibertyAutomation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class privateSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal privateSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibertyAutomation.privateSettings", typeof(privateSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cea0e618-3709-4409-b5a9-5cf8c1ca79b7.
        /// </summary>
        internal static string AppID {
            get {
                return ResourceManager.GetString("AppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://graph.microsoft.com/.default.
        /// </summary>
        internal static string AppScopes {
            get {
                return ResourceManager.GetString("AppScopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NWh8Q~GzOt~bMbum1Fa4iJzRlYxYdHwlNIeORbDT.
        /// </summary>
        internal static string AppSecret {
            get {
                return ResourceManager.GetString("AppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2ae977fc-238e-491f-ba43-5095e226806b.
        /// </summary>
        internal static string AppTenantID {
            get {
                return ResourceManager.GetString("AppTenantID", resourceCulture);
            }
        }
    }
}
